distance = float(input("How long is this journey in Kilometers?: "))
fare_per_km = float(input("How much is this the cost of one kilometre?: "))
total_fare = float(distance * fare_per_km)
real_value = round(total_fare, 2)
# print(real_value)
# print(f"The total amount of travelling {distance } kilometeres from Abuja Drive is {total_fare:.2f} kobo")
print(f"The total amount of travelling {distance } kilometeres from Abuja Drive is {real_value} kobo")